# Hello! Welcome to Acada Learning Class.
name: Hello Workflow

on: 
  push:
    branches: [main, develop,github_workflows]

jobs:
    greet:
          runs-on: ubuntu-latest
          steps:
           - name: Say Hello
             run: echo "Hello from Acada Learning Class!"

